[package]
name = "cc_starknet"
version = "0.1.3"
cairo-version = "2.5.4"

[dependencies]
starknet = "2.5.4"
openzeppelin = { git = "https://github.com/orangeryang/cairo-contracts.git" }
components = { git = "https://github.com/orangeryang/cairo-component.git" }

[[target.starknet-contract]]
# sierra = true
casm = true

[lib]
