[package]
name = "cc_starknet"
version = "0.1.2"
cairo-version = "2.3.1"

[dependencies]
starknet = ">=2.3.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[[target.starknet-contract]]
# sierra = true
casm = true

[lib]
