[package]
name = "cc_starknet"
version = "0.1.1"
cairo-version = "2.3.0"

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }
# graffiti = { git = "https://github.com/milancermak/graffiti.git", tag = "v0.1.0" }

[[target.starknet-contract]]
# sierra = true
casm = true
