[package]
name = "cc_starknet"
version = "0.1.0"

[dependencies]
starknet = ">=2.2.0"
# openzeppelin = { path = "../../openzeppelin" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }

[lib]

[[target.starknet-contract]]
# sierra = true
casm = true
